import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
import {loadTrack,loadTrackRegistry} from '../load_track.js';import {expandConceptBank} from '../../src/logic/questionBank.js';import {contentHash,createContentRelease} from '../../src/platform-kernel/release/releases.js';

const CREATED_AT='2026-09-27T00:00:00Z';
function visible(bundle,q){return{domain:bundle.domains.domains.find(d=>d.id===q.domain_id)?.legacy_keys?.[0]||q.domain_id,topic:q.topic,question:q.question,question_en:q.question_en,options:q.options,options_en:q.options_en,answer:q.answer,explanation:q.explanation,explanation_en:q.explanation_en,difficulty:q.difficulty}}
function sha(value){return crypto.createHash('sha256').update(value).digest('hex')}
function conceptIndex(bundle){const map=new Map();for(const [domainId,concepts] of Object.entries(bundle.concepts))for(const c of concepts){const key=domainId+'\u0000'+c.term;if(map.has(key))throw new Error('Duplicate concept term in domain: '+domainId+':'+c.term);map.set(key,c)}return map}
function objectiveFor(trackId,domainId,concept){return{schema_version:1,objective_id:`${trackId}.objective.${concept.id}.v1`,track_id:trackId,domain_id:domainId,concept_ids:[concept.id],version:1,status:'provisional',origin:'migration-derived'}}
function familyFor(q,objective,concept){return{schema_version:2,family_id:q.family_id,track_id:q.track_id,domain_id:q.domain_id,objective_id:objective.objective_id,concept_ids:[concept.id],misconception_ids:[],learning_goal:`Demonstrate understanding of ${concept.term}`,decision_being_tested:`Select the correct response for ${concept.term}`,cognitive_level:'understand',intended_difficulty:q.difficulty,scenario_model:{type:'migrated-current-rendered-question'},variable_model:{},correct_reasoning:q.explanation_en||q.explanation,common_wrong_reasoning:[],evidence_refs:[],language_requirements:['ar','en'],accessibility_requirements:[],generation_policy:'k1.source.default.v1',quality_policy:'k1.quality.default.v1',release_policy:'k1.review.default.v1',lifecycle:{state:'DRAFT'},version:{number:1}}}
function itemFor(q,provId){return{schema_version:1,item_version_id:q.id,family_id:q.family_id,version:1,content:structuredClone(q),content_hash:contentHash(q),provenance_refs:[provId],release_state:'DRAFT',created_at:CREATED_AT}}
function provenanceFor(q){const h=contentHash(q);return{schema_version:1,record_id:`migration:${q.id}`,record_type:'migration',run_id:'migration:sdaia-current-bank-v1',target_id:q.id,stage:'migration',timestamp:CREATED_AT,input_hash:h,output_hash:h,policy_refs:['k1.source.default.v1','k1.quality.default.v1','k1.review.default.v1'],provider:null}}

export function buildCurrentBankLineage(root){
 const trackId=loadTrackRegistry(root).default_track_id;const bundle=loadTrack(root,trackId);const bank=expandConceptBank(bundle.concepts,{trackId,domainCatalog:bundle.domains});const idx=conceptIndex(bundle);
 const objectives=[];const objectiveByConcept=new Map();for(const [domainId,concepts] of Object.entries(bundle.concepts))for(const concept of concepts){const o=objectiveFor(trackId,domainId,concept);objectives.push(o);objectiveByConcept.set(domainId+'\u0000'+concept.term,o)}
 const families=[];const items=[];const provenanceRecords=[];
 for(const q of bank){const key=q.domain_id+'\u0000'+q.topic;const concept=idx.get(key);const objective=objectiveByConcept.get(key);if(!concept||!objective)throw new Error('Missing concept/objective for '+q.id);const prov=provenanceFor(q);provenanceRecords.push(prov);families.push(familyFor(q,objective,concept));items.push(itemFor(q,prov.record_id))}
 const release=createContentRelease({schema_version:1,release_id:`${trackId}.bootstrap.v1`,track_id:trackId,status:'REVIEW',item_version_ids:items.map(x=>x.item_version_id),source_policy_version:'k1.source.default.v1',quality_policy_version:'k1.quality.default.v1',review_policy_version:'k1.review.default.v1',exam_profile_id:bundle.examProfile.id,exam_profile_version:String(bundle.examProfile.version),created_at:CREATED_AT,origin:'migrated-grandfathered'});
 const sourceRegistry={schema_version:1,track_id:trackId,sources:[]};
 return{trackId,bundle,bank,objectives,families,items,provenanceRecords,qualityReports:[],sourceRegistry,release};
}
export function writeCurrentBankArtifacts(root,outDir){
 const out=buildCurrentBankLineage(root);const files={migration:path.join(outDir,'migrations','sdaia-current-bank-v1.json'),objectives:path.join(outDir,'knowledge','objectives.json'),sources:path.join(outDir,'sources','approved-sources.json'),items:path.join(outDir,'releases','sdaia-bootstrap-v1.items.ndjson'),manifest:path.join(outDir,'releases','sdaia-bootstrap-v1.manifest.json')};for(const file of Object.values(files))fs.mkdirSync(path.dirname(file),{recursive:true});
 const legacyDigest=sha(JSON.stringify(out.bank.map(q=>visible(out.bundle,q))));
 const migration={schema_version:1,migration_id:'sdaia-current-bank-v1',track_id:out.trackId,origin:'migrated-grandfathered',created_at:CREATED_AT,source_rendered_questions:out.bank.length,source_legacy_payload_sha256:legacyDigest,objective_count:out.objectives.length,family_count:out.families.length,item_version_count:out.items.length,quality_reports_created:0,provenance_records:out.provenanceRecords};
 fs.writeFileSync(files.migration,JSON.stringify(migration,null,2)+'\n');fs.writeFileSync(files.objectives,JSON.stringify({schema_version:1,track_id:out.trackId,objectives:out.objectives},null,2)+'\n');fs.writeFileSync(files.sources,JSON.stringify(out.sourceRegistry,null,2)+'\n');fs.writeFileSync(files.items,out.items.map((item,i)=>JSON.stringify({family:out.families[i],item})).join('\n')+'\n');fs.writeFileSync(files.manifest,JSON.stringify(out.release,null,2)+'\n');return files;
}
export function verifyCurrentImport(root,outDir){
 const built=buildCurrentBankLineage(root);const itemsFile=path.join(outDir,'releases','sdaia-bootstrap-v1.items.ndjson');const manifestFile=path.join(outDir,'releases','sdaia-bootstrap-v1.manifest.json');const objectivesFile=path.join(outDir,'knowledge','objectives.json');const migrationFile=path.join(outDir,'migrations','sdaia-current-bank-v1.json');
 const rows=fs.readFileSync(itemsFile,'utf8').trim().split(/\r?\n/).filter(Boolean).map(JSON.parse);const manifest=JSON.parse(fs.readFileSync(manifestFile,'utf8'));const objectives=JSON.parse(fs.readFileSync(objectivesFile,'utf8'));const migration=JSON.parse(fs.readFileSync(migrationFile,'utf8'));const expectedIds=built.bank.map(x=>x.id);const gotIds=rows.map(x=>x.item.item_version_id);const digest=sha(JSON.stringify(rows.map(x=>visible(built.bundle,x.item.content))));
 if(rows.length!==1120||objectives.objectives.length!==140||JSON.stringify(gotIds)!==JSON.stringify(expectedIds)||manifest.item_version_ids.length!==1120||digest!==migration.source_legacy_payload_sha256)throw new Error('Current-bank governed import verification failed');
 return{ok:true,items:rows.length,objectives:objectives.objectives.length,digest,release_id:manifest.release_id};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){const root=process.cwd();const outDir=process.argv[2]?path.resolve(process.argv[2]):path.join(root,'data','factory');const files=writeCurrentBankArtifacts(root,outDir);console.log(JSON.stringify({status:'PASS',files,verification:verifyCurrentImport(root,outDir)}))}
