import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import { expandConceptBank } from '../src/logic/questionBank.js';
import { loadTrack } from '../scripts/load_track.js';
import { ACTIVE_TRACK_ID } from '../src/config.js';
const root=new URL('..',import.meta.url).pathname;const bundle=loadTrack(root,ACTIVE_TRACK_ID);const concepts=bundle.concepts;const q=expandConceptBank(concepts,{trackId:bundle.manifest.id});
const expected=JSON.parse(fs.readFileSync(new URL('./fixtures/runtime/current-bank-counts.expected.json',import.meta.url),'utf8'));
const visible=x=>({domain:x.domain,topic:x.topic,question:x.question,question_en:x.question_en,options:x.options,options_en:x.options_en,answer:x.answer,explanation:x.explanation,explanation_en:x.explanation_en,difficulty:x.difficulty});
test('generated bank matches the versioned compatibility fixture',()=>{assert.equal(q.length,expected.rendered_questions);assert.ok(q.every(x=>x.question&&x.question_en&&x.options.length===4&&x.options_en.length===4))});
test('generated questions use stable namespaced runtime IDs',()=>{const s=q[0];const prefix=bundle.manifest.id.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');assert.match(s.id,new RegExp(`^${prefix}\\.[a-z0-9.-]+\\.v1$`));assert.match(s.family_id,new RegExp(`^${prefix}\\.[a-z0-9.-]+$`));assert.equal(s.track_id,bundle.manifest.id);assert.equal('legacy_id'in s,false)});
test('stable IDs do not depend on concept array order',()=>{const reversed=Object.fromEntries(Object.entries(concepts).map(([d,l])=>[d,[...l].reverse()]));const normal=new Map(expandConceptBank(concepts,{trackId:bundle.manifest.id}).map(x=>[x.id,visible(x)]));const rev=new Map(expandConceptBank(reversed,{trackId:bundle.manifest.id}).map(x=>[x.id,visible(x)]));assert.deepEqual(rev,normal)});
test('question IDs and bilingual prompts are unique',()=>{assert.equal(new Set(q.map(x=>x.id)).size,q.length);assert.equal(new Set(q.map(x=>`${x.domain}|${x.question}|${x.question_en}`)).size,q.length)});
test('canonical answer positions are balanced',()=>{const c=[0,0,0,0];q.forEach(x=>c[x.answer]++);assert.ok(Math.max(...c)-Math.min(...c)<=Math.ceil(q.length*.08),c.join(','))});
test('every domain has the fixture-derived question count',()=>{const c={};q.forEach(x=>c[x.domain]=(c[x.domain]||0)+1);const perDomain=expected.rendered_questions/expected.domains;assert.equal(Number.isInteger(perDomain),true);Object.values(c).forEach(n=>assert.equal(n,perDomain))});
test('educational payload stays byte-for-byte compatible',()=>{const digest=crypto.createHash('sha256').update(JSON.stringify(q.map(visible))).digest('hex');assert.equal(digest,expected.legacy_payload_sha256)});
test('legacy generated ID map covers the full shipped bank exactly once',()=>{const map=JSON.parse(fs.readFileSync(new URL('../data/migrations/sdaia-generated-v2-question-ids.json',import.meta.url),'utf8'));assert.equal(Object.keys(map).length,expected.rendered_questions);assert.equal(new Set(Object.values(map)).size,expected.rendered_questions);assert.equal(map.q1,q[0].id);const last=`q${expected.rendered_questions}`;assert.equal(map[last],q.at(-1).id)});
