import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import { expandConceptBank } from '../src/logic/questionBank.js';
import { loadTrack } from '../scripts/load_track.js';
const root=new URL('..',import.meta.url).pathname;const bundle=loadTrack(root,'sdaia-ai-engineer');const concepts=bundle.concepts;const q=expandConceptBank(concepts,{trackId:bundle.manifest.id});
const expected=JSON.parse(fs.readFileSync(new URL('./fixtures/runtime/current-bank-counts.expected.json',import.meta.url),'utf8'));
const visible=x=>({domain:x.domain,topic:x.topic,question:x.question,question_en:x.question_en,options:x.options,options_en:x.options_en,answer:x.answer,explanation:x.explanation,explanation_en:x.explanation_en,difficulty:x.difficulty});
test('generated bank has 1120 bilingual questions',()=>{assert.equal(q.length,1120);assert.ok(q.every(x=>x.question&&x.question_en&&x.options.length===4&&x.options_en.length===4))});
test('generated questions use stable namespaced runtime IDs',()=>{const s=q[0];assert.match(s.id,/^sdaia-ai-engineer\.[a-z0-9.-]+\.v1$/);assert.match(s.family_id,/^sdaia-ai-engineer\.[a-z0-9.-]+$/);assert.equal(s.track_id,'sdaia-ai-engineer');assert.equal('legacy_id'in s,false)});
test('stable IDs do not depend on concept array order',()=>{const reversed=Object.fromEntries(Object.entries(concepts).map(([d,l])=>[d,[...l].reverse()]));const normal=new Map(expandConceptBank(concepts,{trackId:'sdaia-ai-engineer'}).map(x=>[x.id,visible(x)]));const rev=new Map(expandConceptBank(reversed,{trackId:'sdaia-ai-engineer'}).map(x=>[x.id,visible(x)]));assert.deepEqual(rev,normal)});
test('question IDs and bilingual prompts are unique',()=>{assert.equal(new Set(q.map(x=>x.id)).size,q.length);assert.equal(new Set(q.map(x=>`${x.domain}|${x.question}|${x.question_en}`)).size,q.length)});
test('canonical answer positions are balanced',()=>{const c=[0,0,0,0];q.forEach(x=>c[x.answer]++);assert.ok(Math.max(...c)-Math.min(...c)<=Math.ceil(q.length*.08),c.join(','))});
test('every domain has 160 questions',()=>{const c={};q.forEach(x=>c[x.domain]=(c[x.domain]||0)+1);Object.values(c).forEach(n=>assert.equal(n,160))});
test('educational payload stays byte-for-byte compatible',()=>{const digest=crypto.createHash('sha256').update(JSON.stringify(q.map(visible))).digest('hex');assert.equal(digest,expected.legacy_payload_sha256)});
test('legacy generated ID map covers the full shipped bank exactly once',()=>{const map=JSON.parse(fs.readFileSync(new URL('../data/migrations/sdaia-generated-v2-question-ids.json',import.meta.url),'utf8'));assert.equal(Object.keys(map).length,1120);assert.equal(new Set(Object.values(map)).size,1120);assert.equal(map.q1,q[0].id);assert.equal(map.q1120,q[1119].id)});
