import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { expandConceptBank } from '../src/logic/questionBank.js';
import { weightedAllocation, sampleWeightedExam, sampleSectionExam, buildOptionOrders, scoreExam } from '../src/logic/exam.js';
import { loadConcepts } from '../scripts/load_concepts.js';
const concepts=loadConcepts(new URL('..',import.meta.url).pathname);
const questions=expandConceptBank(concepts);
const weights=JSON.parse(fs.readFileSync(new URL('../data/weights.json', import.meta.url),'utf8'));
test('200-question weighted allocation is exact',()=>{assert.deepEqual(weightedAllocation(weights,200),{'MLOps / LLMOps':36,'Data / ML / Evaluation':35,'Core AI / Deep Learning / GenAI':33,'Responsible AI / Security / Governance':29,'AI Software Engineering':28,'Architecture / Infrastructure':25,'Business / Professional Practice':14})});
test('full exam contains 200 unique questions with weighted domains',()=>{const exam=sampleWeightedExam(questions,weights,200,()=>.42);assert.equal(exam.length,200);assert.equal(new Set(exam.map(q=>q.id)).size,200);const a={};exam.forEach(q=>a[q.domain]=(a[q.domain]||0)+1);assert.deepEqual(a,weightedAllocation(weights,200))});
test('section exam stays inside requested domain',()=>{const d='MLOps / LLMOps';const exam=sampleSectionExam(questions,d,50,()=>.33);assert.equal(exam.length,50);assert.ok(exam.every(q=>q.domain===d))});
test('option orders are permutations',()=>{const o=buildOptionOrders(questions.slice(0,100),()=>.37);for(const q of questions.slice(0,100))assert.deepEqual([...o[q.id]].sort(),[0,1,2,3])});
test('a 200-question exam balances displayed correct answers exactly across A/B/C/D',()=>{const exam=sampleWeightedExam(questions,weights,200,()=>.42);let seed=123456789;const rng=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296};const orders=buildOptionOrders(exam,rng);const counts=[0,0,0,0];for(const q of exam){const display=orders[q.id].indexOf(q.answer);counts[display]++}assert.deepEqual(counts,[50,50,50,50])});
test('confidence is not required by scoring',()=>{const exam=questions.slice(0,3),answers={[exam[0].id]:exam[0].answer,[exam[1].id]:exam[1].answer};const s=scoreExam(exam,answers);assert.equal(s.correct,2);assert.equal(s.unanswered,1)});
