import test from 'node:test';
import assert from 'node:assert/strict';
class FakeLocalStorage {constructor(){this.map=new Map()}getItem(k){return this.map.has(k)?this.map.get(k):null}setItem(k,v){this.map.set(k,String(v))}removeItem(k){this.map.delete(k)}}
const UUID_V4=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
test('browser adapter saves and loads state with localStorage',async()=>{globalThis.localStorage=new FakeLocalStorage();globalThis.location={protocol:'https:'};const a=await import('../src/storage/browser.js');await a.saveState({sample:true});const l=await a.loadState();assert.equal(l.sample,true);assert.match(l.anon_id,UUID_V4)});
test('browser adapter bootstraps a fresh state before app startup',async()=>{globalThis.localStorage=new FakeLocalStorage();globalThis.location={protocol:'https:'};const a=await import('../src/storage/browser.js');const l=await a.loadState();assert.match(l.anon_id,UUID_V4);assert.ok(globalThis.localStorage.getItem('sdaia.state.v1'))});
test('browser adapter recovers from unreadable saved state',async()=>{globalThis.localStorage=new FakeLocalStorage();globalThis.location={protocol:'https:'};globalThis.localStorage.setItem('sdaia.state.v1','{broken-json');const a=await import('../src/storage/browser.js');const l=await a.loadState();assert.match(l.anon_id,UUID_V4);assert.doesNotThrow(()=>JSON.parse(globalThis.localStorage.getItem('sdaia.state.v1')))});
test('browser adapter loads concept bank over fetch',async()=>{globalThis.localStorage=new FakeLocalStorage();globalThis.location={protocol:'https:'};globalThis.fetch=async url=>({ok:true,json:async()=>url.includes('/concepts/')?{domain:url,concepts:[]}:{url}});const a=await import('../src/storage/browser.js');const bank=await a.loadBank();assert.equal(Object.keys(bank).length,5);assert.equal(Object.keys(bank.concepts).length,7)});
test('browser adapter falls back to inline bank when network loading fails',async()=>{globalThis.localStorage=new FakeLocalStorage();globalThis.location={protocol:'https:'};globalThis.fetch=async()=>{throw new Error('offline')};const inline={concepts:{sample:[]},sessions:[],learn:{},cases:[],weights:{sample:100}};globalThis.document={getElementById(id){return id==='inline-bank'?{textContent:JSON.stringify(inline)}:null}};const a=await import('../src/storage/browser.js');assert.deepEqual(await a.loadBank(),inline)});
