import { evaluateEventPrivacy } from './privacyPolicy.js';
import { getEventDefinition, validateEvent } from './eventRegistry.js';

const ENVELOPE_FIELDS = new Set([
  'definition_id',
  'track_id',
  'content_release_id',
  'mode',
  'locale',
  'activity_id',
  'assessment_attempt_id',
  'form_id',
  'item_version_id',
  'objective_id',
  'domain_id'
]);

function nonEmpty(value){ return typeof value === 'string' && value.trim().length > 0; }
function uuid4(value){ return typeof value === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value); }

function assertLearnerDefinition(event, definition){
  if(!event || typeof event !== 'object') throw new TypeError('learner evidence event is required');
  if(!definition || typeof definition !== 'object') throw new TypeError('learner evidence definition is required');
  const id=`${definition.event_name}@${definition.event_version}`;
  if(definition.plane !== 'LEARNER_EVIDENCE' || id !== event.definition_id){
    throw new Error('learner evidence definition does not match event');
  }
  if(!event.payload || typeof event.payload !== 'object' || Array.isArray(event.payload)){
    throw new TypeError('learner evidence payload is required');
  }
  if(!nonEmpty(event.occurred_at) || Number.isNaN(Date.parse(event.occurred_at))){
    throw new TypeError('learner evidence occurred_at is required');
  }
}

function sourceValue(rule, event, sanitizedPayload, definition){
  if(!rule || typeof rule !== 'object' || Array.isArray(rule)){
    throw new TypeError('analytics mapping rule is required');
  }
  if(Object.hasOwn(rule,'constant')){
    return {present:true,value:structuredClone(rule.constant)};
  }
  if(!nonEmpty(rule.from)) throw new TypeError('analytics mapping source is required');
  const [scope,key,...rest]=rule.from.split('.');
  if(rest.length || !key) throw new Error(`Unsupported analytics mapping source: ${rule.from}`);
  if(scope === 'payload'){
    if(!Object.hasOwn(definition.properties ?? {},key)){
      throw new Error(`Analytics mapping source is not governed: ${rule.from}`);
    }
    if(!Object.hasOwn(sanitizedPayload,key)) return {present:false};
    return {present:true,value:structuredClone(sanitizedPayload[key])};
  }
  if(scope === 'envelope'){
    if(!ENVELOPE_FIELDS.has(key)) throw new Error(`Unsupported analytics envelope source: ${rule.from}`);
    if(!Object.hasOwn(event,key) || event[key] === undefined) return {present:false};
    return {present:true,value:structuredClone(event[key])};
  }
  throw new Error(`Unsupported analytics mapping source: ${rule.from}`);
}

export function toAnalyticsEvent(evidenceEvent, definition, mapping, options = {}){
  assertLearnerDefinition(evidenceEvent,definition);
  if(!mapping || typeof mapping !== 'object' || !nonEmpty(mapping.mapping_version)){
    throw new TypeError('versioned analytics mapping is required');
  }
  if(!nonEmpty(mapping.analytics_definition_id) || !mapping.properties || typeof mapping.properties !== 'object' || Array.isArray(mapping.properties)){
    throw new TypeError('analytics mapping definition and properties are required');
  }

  const privacy=evaluateEventPrivacy(definition,evidenceEvent.payload);
  if(privacy.decision === 'REJECT') return null;

  const analyticsDefinition=getEventDefinition(mapping.analytics_definition_id);
  if(!analyticsDefinition) throw new Error('Unknown analytics definition');
  if(analyticsDefinition.plane === 'LEARNER_EVIDENCE') throw new Error('Analytics mapping target cannot be learner evidence');
  if(!Object.hasOwn(analyticsDefinition.properties ?? {},'analytics_event_id')){
    throw new Error('Analytics definition must govern analytics_event_id');
  }

  const crypto=options.crypto ?? globalThis.crypto;
  if(!crypto || typeof crypto.randomUUID !== 'function') throw new TypeError('crypto.randomUUID is required');
  const analyticsId=crypto.randomUUID();
  if(!uuid4(analyticsId) || analyticsId === evidenceEvent.event_id){
    throw new Error('analytics event identity must be a separate UUIDv4');
  }

  const properties={analytics_event_id:analyticsId};
  for(const [target,rule] of Object.entries(mapping.properties)){
    if(target === 'analytics_event_id') throw new Error('analytics_event_id is generated by the bridge');
    if(!Object.hasOwn(analyticsDefinition.properties ?? {},target)){
      throw new Error(`Analytics mapping target is not governed: ${target}`);
    }
    const resolved=sourceValue(rule,evidenceEvent,privacy.payload,definition);
    if(resolved.present) properties[target]=resolved.value;
  }

  return validateEvent(mapping.analytics_definition_id,{
    occurred_at:evidenceEvent.occurred_at,
    properties
  });
}
