import { ACTIVE_TRACK_ID } from '../config.js';
const STATE_KEY='learning-platform.state.v2';const LEGACY_STATE_KEYS=['sdaia.state.v1','sdaia_adaptive_v3'];const memory=new Map();
function storageAccess(){try{const k='__lp_storage_probe__';globalThis.localStorage.setItem(k,'1');globalThis.localStorage.removeItem(k);return globalThis.localStorage}catch{return null}}
function readRaw(storage,key){return storage?storage.getItem(key):(memory.has(key)?memory.get(key):null)}function writeRaw(storage,key,value){if(storage)storage.setItem(key,value);else memory.set(key,value)}
export async function loadState(){const storage=storageAccess();for(const key of [STATE_KEY,...LEGACY_STATE_KEYS]){const raw=readRaw(storage,key);if(!raw)continue;try{return JSON.parse(raw)}catch{continue}}return null}
export async function saveState(state){writeRaw(storageAccess(),STATE_KEY,JSON.stringify(state))}
export async function loadBank(){const protocol=globalThis.location?.protocol??'file:';if(protocol==='file:')throw new Error('Run the study site through HTTP so track content can be loaded.');const {loadRuntimeBundle}=await import('../content/runtimeBundle.js');const loadJson=async url=>{const r=await fetch(url,{cache:'no-cache'});if(!r.ok)throw new Error(`Failed to load ${url}: ${r.status}`);return r.json()};return loadRuntimeBundle(loadJson,ACTIVE_TRACK_ID)}
export async function submitFeedback(item){const questionId=String(item?.question_id??'unknown');const issueType=String(item?.issue_type??'other');const params=new URLSearchParams({template:'question-report.yml',title:`Question report: ${questionId} [${issueType}]`,question_id:questionId,issue_type:issueType});return{ok:true,ref:`https://github.com/oaabahussain/sdaia-ai-engineer/issues/new?${params.toString()}`}}
export async function logEvent(_evt){}
