import { registerServiceWorker } from './registerServiceWorker.js';
import { loadState, saveState, loadBank } from './storage/interface.js';
import { weightedAllocation, sampleWeightedExam, sampleSectionExam, buildOptionOrders, scoreExam } from './logic/exam.js';
import { expandConceptBank } from './logic/questionBank.js';
import { CORE_I18N, CORE_DEFAULT_LOCALE } from './presentation/coreI18n.js';
import { loadTrackPresentation, resolvePresentationLocale, getPresentationLocale } from './presentation/trackPresentation.js';

registerServiceWorker();

const TRACK_I18N = {
 ar:{brand:'SDAIA AI Engineer · بنك الاختبارات',eyebrow:'بنك اختبارات ثنائي اللغة',heroTitle:'تدرّب مثل الاختبار، بدون نمط محفوظ للإجابات.',heroText:'أكثر من ألف سؤال بالعربي والإنجليزي، اختبار كامل موزون، واختبارات مستقلة لكل مجال.',unofficial:'أداة تحضيرية مستقلة وغير رسمية. أوزان المجالات مبنية على مرجع المشروع، وبنك الأسئلة محتوى تدريبي للممارسة.'},
 en:{brand:'SDAIA AI Engineer · Exam Bank',eyebrow:'Bilingual exam bank',heroTitle:'Practice like an exam, without a predictable answer pattern.',heroText:'More than one thousand Arabic/English questions, a weighted full exam, and standalone domain exams.',unofficial:'An independent, unofficial preparation tool. Domain weights follow the project reference, and the question bank is training content for practice.'}
};

const DOMAIN_AR={
 'MLOps / LLMOps':'عمليات تعلم الآلة والنماذج اللغوية',
 'Data / ML / Evaluation':'البيانات وتعلم الآلة والتقييم',
 'Core AI / Deep Learning / GenAI':'أساسيات الذكاء الاصطناعي والتعلم العميق والذكاء التوليدي',
 'Responsible AI / Security / Governance':'الذكاء المسؤول والأمن والحوكمة',
 'AI Software Engineering':'هندسة برمجيات الذكاء الاصطناعي',
 'Architecture / Infrastructure':'المعمارية والبنية التحتية',
 'Business / Professional Practice':'الأعمال والممارسة المهنية',
};

const $=id=>document.getElementById(id);
let BANK, PROFILE, QUESTIONS=[], WEIGHTS={}, state, lang='ar', activeExam=null;
let PRESENTATION=null;
function trackState(){return state.tracks[BANK.track.id]}

function t(key,...args){const v=CORE_I18N[lang]?.app?.[key]??TRACK_I18N[lang]?.[key];return typeof v==='function'?v(...args):(v??key)}
function presentationView(){let locale=CORE_I18N[lang]?lang:CORE_DEFAULT_LOCALE;if(PRESENTATION&&BANK?.track){try{locale=resolvePresentationLocale(lang,BANK.track,PRESENTATION)}catch(presentationError){console.warn('Presentation locale fallback',presentationError)}}const view=getPresentationLocale(PRESENTATION,locale);const fallbackName=BANK?.track?.id??'learning-platform';return{locale,view,displayName:view?.display_name??fallbackName,brand:view?.brand??fallbackName}}
function domainLabel(domain){return lang==='ar'?(DOMAIN_AR[domain]||domain):domain}
function secureRng(){if(globalThis.crypto?.getRandomValues){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296}return Math.random()}
function save(){state.preferences.lang=lang;state.preferences.theme=document.documentElement.dataset.theme||'light';trackState().active_exam=activeExam;state.updated_at=new Date().toISOString();void saveState(state)}
function showScreen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');scrollTo({top:0,behavior:'smooth'})}
function qById(id){return QUESTIONS.find(q=>q.id===id)}
function localizedQuestion(q){return lang==='ar'?q.question:q.question_en}
function localizedOptions(q){return lang==='ar'?q.options:q.options_en}
function localizedExplanation(q){return lang==='ar'?q.explanation:q.explanation_en}

function applyLanguage(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';$('langBtn').textContent=lang==='ar'?'EN':'العربية';document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;const v=CORE_I18N[lang]?.app?.[key]??TRACK_I18N[lang]?.[key];if(v&&typeof v!=='function')el.textContent=t(key)});renderHome();if($('exam').classList.contains('active'))renderExam();if($('results').classList.contains('active'))renderResults(lastResult)}
function applyTheme(theme){document.documentElement.dataset.theme=theme;$('themeBtn').textContent=theme==='dark'?'🌙':'☀️';save()}

function renderAllocation(){const allocation=weightedAllocation(WEIGHTS,PROFILE.question_count);$('allocation').innerHTML=Object.entries(allocation).map(([d,n])=>`<div class="allocRow"><div><b>${domainLabel(d)}</b><div class="bar"><i style="width:${WEIGHTS[d]}%"></i></div></div><span>${n} · ${WEIGHTS[d]}%</span></div>`).join('')}
function renderDomains(){const counts=Object.fromEntries(Object.keys(WEIGHTS).map(d=>[d,QUESTIONS.filter(q=>q.domain===d).length]));const preferred=PROFILE.section_sizes.includes(50)?50:PROFILE.section_sizes.find(x=>x!=='all');$('domainGrid').innerHTML=Object.entries(WEIGHTS).map(([d,w],i)=>`<div class="card domainCard"><div class="eyebrow">${String(i+1).padStart(2,'0')}</div><h3>${domainLabel(d)}</h3><div class="domainMeta"><span class="chip">${t('weight')} ${w}%</span><span class="chip">${t('bank')} ${counts[d]}</span></div><div class="domainActions"><select class="select sectionCount" data-domain="${d}">${PROFILE.section_sizes.map(size=>`<option value="${size}" ${size===preferred?'selected':''}>${size==='all'?`${t('all')} (${counts[d]})`:size}</option>`).join('')}</select><button class="btn primary startSection" data-domain="${d}">${t('start')}</button></div></div>`).join('');document.querySelectorAll('.startSection').forEach(btn=>btn.onclick=()=>{const d=btn.dataset.domain;const sel=[...document.querySelectorAll('.sectionCount')].find(x=>x.dataset.domain===d);startSection(d,sel.value)})}
function renderHome(){if(!BANK)return;const domainCount=Object.keys(WEIGHTS).length;$('bankCount').textContent=QUESTIONS.length;$('domainCount').textContent=domainCount;$('fullExamCount').textContent=PROFILE.question_count;$('fullExamTitle').textContent=t('weightedExam',PROFILE.question_count);$('fullExamDesc').textContent=t('weightedDesc',domainCount);$('startFullBtn').textContent=t('startFull',PROFILE.question_count);renderAllocation();renderDomains();$('domainSummary').innerHTML=`<div class="stats"><div class="stat"><b>${QUESTIONS.length}</b><small>${t('questions')}</small></div><div class="stat"><b>${Object.keys(WEIGHTS).length}</b><small>${t('domains')}</small></div></div>`;const box=$('resumeBox');if(activeExam&&!activeExam.submitted){box.classList.add('show');$('resumeMeta').textContent=t('resumeText',activeExam.index+1,activeExam.questionIds.length)}else box.classList.remove('show')}

function createExam(mode, questions, domain=null){activeExam={id:`exam-${Date.now()}-${Math.floor(secureRng()*1e6)}`,mode,domain,track_id:BANK.track.id,track_version:BANK.track.version,exam_profile_id:BANK.exam_profile.id,exam_profile_version:BANK.exam_profile.version,questionIds:questions.map(q=>q.id),index:0,answers:{},confidence:{},flags:{},optionOrders:buildOptionOrders(questions,secureRng),started_at:new Date().toISOString(),submitted:false};save();showScreen('exam');renderExam()}
function startFull(){createExam('full',sampleWeightedExam(QUESTIONS,WEIGHTS,PROFILE.question_count,secureRng))}
function startSection(domain,count){createExam('section',sampleSectionExam(QUESTIONS,domain,count,secureRng),domain)}

function selectAnswer(canonicalIndex){const q=qById(activeExam.questionIds[activeExam.index]);activeExam.answers[q.id]=canonicalIndex;save();renderExam()}
function setConfidence(value){const q=qById(activeExam.questionIds[activeExam.index]);if(value==='clear')delete activeExam.confidence[q.id];else if(activeExam.confidence[q.id]===value)delete activeExam.confidence[q.id];else activeExam.confidence[q.id]=value;save();renderExam()}
function move(delta){const next=Math.max(0,Math.min(activeExam.questionIds.length-1,activeExam.index+delta));activeExam.index=next;save();renderExam();scrollTo({top:0,behavior:'smooth'})}
function jump(i){activeExam.index=i;save();renderExam();scrollTo({top:0,behavior:'smooth'})}
function toggleFlag(){const id=activeExam.questionIds[activeExam.index];activeExam.flags[id]=!activeExam.flags[id];if(!activeExam.flags[id])delete activeExam.flags[id];save();renderExam()}

function renderExam(){if(!activeExam)return;const q=qById(activeExam.questionIds[activeExam.index]);if(!q)return;const total=activeExam.questionIds.length;const answered=Object.keys(activeExam.answers).length;$('examModeLabel').textContent=activeExam.mode==='full'?t('fullMode'):t('sectionMode');$('examDomainChip').textContent=activeExam.mode==='full'?`${Object.keys(WEIGHTS).length} ${t('domains')}`:domainLabel(activeExam.domain);$('answeredChip').textContent=`${t('answered')} ${answered}/${total}`;$('examProgress').style.width=`${(activeExam.index+1)/total*100}%`;$('qTopic').textContent=`${domainLabel(q.domain)} · ${q.topic}`;$('qText').textContent=localizedQuestion(q);$('questionCounter').textContent=`${activeExam.index+1} ${t('of')} ${total}`;const localized=localizedOptions(q);const order=activeExam.optionOrders[q.id]||[0,1,2,3];$('options').innerHTML=order.map((canonical,display)=>`<button class="option ${Number(activeExam.answers[q.id])===canonical?'selected':''}" data-answer="${canonical}" aria-pressed="${Number(activeExam.answers[q.id])===canonical}"><span class="letter">${String.fromCharCode(65+display)}</span><span>${localized[canonical]}</span></button>`).join('');document.querySelectorAll('.option').forEach(b=>b.onclick=()=>selectAnswer(Number(b.dataset.answer)));document.querySelectorAll('.confBtn').forEach(b=>b.classList.toggle('on',b.dataset.confidence!=='clear'&&activeExam.confidence[q.id]===b.dataset.confidence));$('flagBtn').textContent=activeExam.flags[q.id]?t('unflag'):t('flag');$('prevBtn').disabled=activeExam.index===0;$('nextBtn').disabled=activeExam.index===total-1;$('palette').innerHTML=activeExam.questionIds.map((id,i)=>`<button class="qjump ${i===activeExam.index?'current':''} ${activeExam.answers[id]!==undefined?'answered':''} ${activeExam.flags[id]?'flagged':''}" data-index="${i}" aria-label="${i+1}">${i+1}</button>`).join('');document.querySelectorAll('.qjump').forEach(b=>b.onclick=()=>jump(Number(b.dataset.index)))}

let lastResult=null;
function submitExam(){if(!activeExam)return;if(!confirm(t('confirmSubmit')))return;const qs=activeExam.questionIds.map(qById).filter(Boolean);const result=scoreExam(qs,activeExam.answers);activeExam.submitted=true;activeExam.submitted_at=new Date().toISOString();trackState().exam_history.unshift({attempt:{...structuredClone(activeExam),submitted:true,submitted_at:activeExam.submitted_at},result});trackState().exam_history=trackState().exam_history.slice(0,20);lastResult={result,exam:structuredClone(activeExam),questions:qs};activeExam=null;save();showScreen('results');renderResults(lastResult)}
function renderResults(payload){if(!payload)return;const {result,exam,questions}=payload;$('scorePct').textContent=`${result.percent}%`;$('scoreLabel').textContent=t('scoreText',result.correct,result.total);$('correctKpi').textContent=result.correct;$('wrongKpi').textContent=result.answered-result.correct;$('unansweredKpi').textContent=result.unanswered;const confUsed=Object.keys(exam.confidence||{}).length;$('confidenceKpi').textContent=`${Math.round(confUsed/result.total*100)}%`;$('resultBreakdown').innerHTML=Object.entries(result.perDomain).map(([d,v])=>{const pct=v.total?Math.round(v.correct/v.total*1000)/10:0;return `<div><div class="allocRow"><b>${domainLabel(d)}</b><span>${v.correct}/${v.total} · ${pct}%</span></div><div class="bar"><i style="width:${pct}%"></i></div></div>`}).join('');$('reviewList').innerHTML=questions.map((q,i)=>{const a=exam.answers[q.id];const opts=localizedOptions(q);const answerText=a===undefined?t('notAnswered'):opts[a];const good=Number(a)===q.answer;return `<div class="reviewItem"><div class="qTopic">${i+1}. ${domainLabel(q.domain)} · ${q.topic}</div><b>${localizedQuestion(q)}</b><div class="${good?'answerGood':'answerBad'}"><strong>${t('yourAnswer')}:</strong> ${answerText}</div>${good?'':`<div class="answerGood"><strong>${t('correctAnswer')}:</strong> ${opts[q.answer]}</div>`}<div class="muted">${localizedExplanation(q)}</div></div>`}).join('')}

function resetToHome(){showScreen('home');renderHome()}

$('langBtn').onclick=()=>{lang=lang==='ar'?'en':'ar';save();applyLanguage()};$('themeBtn').onclick=()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');$('homeBtn').onclick=resetToHome;$('startFullBtn').onclick=startFull;$('resumeBtn').onclick=()=>{if(activeExam){showScreen('exam');renderExam()}};$('prevBtn').onclick=()=>move(-1);$('nextBtn').onclick=()=>move(1);$('flagBtn').onclick=toggleFlag;$('submitBtn').onclick=submitExam;$('newExamBtn').onclick=resetToHome;document.querySelectorAll('.confBtn').forEach(b=>b.onclick=()=>setConfidence(b.dataset.confidence));
window.addEventListener('keydown',e=>{if(!$('exam').classList.contains('active')||!activeExam)return;if(['1','2','3','4'].includes(e.key)){const q=qById(activeExam.questionIds[activeExam.index]);const order=activeExam.optionOrders[q.id]||[0,1,2,3];selectAnswer(order[Number(e.key)-1])}else if(e.key==='ArrowRight')move(lang==='ar'?-1:1);else if(e.key==='ArrowLeft')move(lang==='ar'?1:-1)});

async function init(){try{BANK=await loadBank();const fetchJson=async url=>{const response=await fetch(url,{cache:'no-cache'});if(!response.ok)throw new Error(`Failed to load ${url}: ${response.status}`);return response.json()};try{PRESENTATION=await loadTrackPresentation(fetchJson,BANK.track)}catch(presentationError){console.warn('Track presentation unavailable',presentationError);PRESENTATION=null}PROFILE=BANK.exam_profile;if(!PROFILE)throw new Error('Missing exam profile');QUESTIONS=expandConceptBank(BANK.concepts||{},{trackId:BANK.track.id});WEIGHTS=PROFILE.weights;if(QUESTIONS.length<PROFILE.question_count)throw new Error(t('errorBank'));const mapResponse=await fetch('./data/migrations/sdaia-generated-v2-question-ids.json',{cache:'no-cache'});if(!mapResponse.ok)throw new Error('Failed to load question ID migration map');const questionIdMap=await mapResponse.json();state=await loadState({questionIdMap,trackId:BANK.track.id,trackVersion:BANK.track.version,examProfileId:BANK.exam_profile.id,examProfileVersion:BANK.exam_profile.version});lang=state.preferences.lang==='en'?'en':'ar';activeExam=trackState().active_exam&&!trackState().active_exam.submitted?trackState().active_exam:null;document.documentElement.dataset.theme=state.preferences.theme==='dark'?'dark':'light';$('themeBtn').textContent=document.documentElement.dataset.theme==='dark'?'🌙':'☀️';applyLanguage();renderHome()}catch(error){console.error(error);$('errorBox').textContent=error.message||String(error);$('errorBox').classList.add('show')}}
init();
