import { loadState, saveState, loadBank } from './storage/interface.js';
import { weightedAllocation, sampleWeightedExam, sampleSectionExam, buildOptionOrders, scoreExam } from './logic/exam.js';
import { expandConceptBank } from './logic/questionBank.js';

const I18N = {
 ar:{brand:'SDAIA AI Engineer · بنك الاختبارات',home:'الرئيسية',eyebrow:'بنك اختبارات ثنائي اللغة',heroTitle:'تدرّب مثل الاختبار، بدون نمط محفوظ للإجابات.',heroText:'أكثر من ألف سؤال بالعربي والإنجليزي، اختبار كامل موزون، واختبارات مستقلة لكل مجال.',questions:'سؤال',domains:'مجالات',fullExam:'الاختبار الكامل',randomized:'خيارات عشوائية',resumeAvailable:'لديك اختبار غير مكتمل',resume:'استأنف',rules:'قواعد الاختبار',rulesTitle:'مصمم لكسر الأنماط',rule1:'ترتيب الأسئلة يتغير مع كل محاولة.',rule2:'ترتيب A/B/C/D يتغير لكل سؤال مع كل محاولة.',rule3:'الثقة اختيارية ولا تمنع الانتقال أو التسليم.',rule4:'يمكنك تغيير اللغة أثناء الاختبار بدون فقد الإجابة.',unofficial:'هذه أداة تحضيرية غير رسمية. الأوزان مأخوذة من المرجع الذي زودتني به، أما بنك الأسئلة فهو محتوى تدريبي.',mode:'وضع الاختبار',chooseExam:'اختر طريقة الاختبار',weighted200:'اختبار كامل — 200 سؤال موزون',weightedDesc:'يتم سحب الأسئلة من المجالات السبعة بنفس الأوزان ثم خلطها.',startFull:'ابدأ اختبار 200 سؤال',sectionExam:'اختبار مجال واحد',sectionDesc:'اختر أي مجال واختبر نفسك فيه وحده.',sections:'المجالات',sectionTests:'اختبارات مستقلة لكل قسم',start:'ابدأ',bank:'بنك',weight:'الوزن',count:'عدد الأسئلة',all:'الكل',flag:'⚑ علّم السؤال',unflag:'✓ أزل العلامة',confidenceOptional:'مستوى الثقة — اختياري',confidenceNote:'اتركه بدون اختيار إذا لم ترغب باستخدامه.',low:'غير واثق',medium:'متوسط',high:'واثق',clear:'مسح',previous:'السابق',next:'التالي',submitExam:'تسليم الاختبار',navigation:'التنقل',keyboardHint:'اختصارات: 1–4 للإجابة، والأسهم للتنقل.',result:'النتيجة',correct:'صحيح',wrong:'خطأ',unanswered:'بدون إجابة',confidenceUsed:'استخدمت الثقة',domainBreakdown:'النتيجة حسب المجال',reviewAnswers:'مراجعة الإجابات',newExam:'اختبار جديد',footer:'الأسئلة التدريبية غير رسمية · التقدم محفوظ محلياً على جهازك.',answered:'مجاب',of:'من',fullMode:'اختبار كامل موزون',sectionMode:'اختبار مجال',confirmSubmit:'هل تريد تسليم الاختبار الآن؟ يمكنك ترك أسئلة بلا إجابة.',scoreText:(c,t)=>`${c} إجابة صحيحة من ${t}`,yourAnswer:'إجابتك',correctAnswer:'الإجابة الصحيحة',notAnswered:'لم تتم الإجابة',resumeText:(i,t)=>`السؤال ${i} من ${t}`,errorBank:'تعذر تحميل بنك الأسئلة الكامل. حدّث الصفحة وتأكد من الاتصال بالإنترنت.'},
 en:{brand:'SDAIA AI Engineer · Exam Bank',home:'Home',eyebrow:'Bilingual exam bank',heroTitle:'Practice like an exam, without a predictable answer pattern.',heroText:'More than one thousand Arabic/English questions, a weighted full exam, and standalone domain exams.',questions:'Questions',domains:'Domains',fullExam:'Full exam',randomized:'Random options',resumeAvailable:'You have an unfinished exam',resume:'Resume',rules:'Exam rules',rulesTitle:'Designed to break patterns',rule1:'Question order changes on every attempt.',rule2:'A/B/C/D order changes for every question on every attempt.',rule3:'Confidence is optional and never blocks navigation or submission.',rule4:'You can switch language during the exam without losing your answer.',unofficial:'This is an unofficial preparation tool. Domain weights come from the reference you provided; the question bank is training content.',mode:'Exam mode',chooseExam:'Choose how you want to test',weighted200:'Full exam — 200 weighted questions',weightedDesc:'Questions are sampled from all seven domains using the weights, then shuffled.',startFull:'Start 200-question exam',sectionExam:'Single-domain exam',sectionDesc:'Choose any domain and test it independently.',sections:'Domains',sectionTests:'Standalone exams by section',start:'Start',bank:'Bank',weight:'Weight',count:'Questions',all:'All',flag:'⚑ Flag question',unflag:'✓ Remove flag',confidenceOptional:'Confidence — optional',confidenceNote:'Leave it blank if you do not want to use confidence.',low:'Low',medium:'Medium',high:'High',clear:'Clear',previous:'Previous',next:'Next',submitExam:'Submit exam',navigation:'Navigation',keyboardHint:'Shortcuts: 1–4 to answer, arrow keys to navigate.',result:'Result',correct:'Correct',wrong:'Wrong',unanswered:'Unanswered',confidenceUsed:'Confidence used',domainBreakdown:'Result by domain',reviewAnswers:'Review answers',newExam:'New exam',footer:'Training questions are unofficial · Progress is stored locally on your device.',answered:'Answered',of:'of',fullMode:'Weighted full exam',sectionMode:'Domain exam',confirmSubmit:'Submit the exam now? You may leave questions unanswered.',scoreText:(c,t)=>`${c} correct out of ${t}`,yourAnswer:'Your answer',correctAnswer:'Correct answer',notAnswered:'Not answered',resumeText:(i,t)=>`Question ${i} of ${t}`,errorBank:'The full question bank could not be loaded. Refresh the page and check your connection.'}
};

const DOMAIN_AR={
 'MLOps / LLMOps':'عمليات تعلم الآلة والنماذج اللغوية',
 'Data / ML / Evaluation':'البيانات وتعلم الآلة والتقييم',
 'Core AI / Deep Learning / GenAI':'أساسيات الذكاء الاصطناعي والتعلم العميق والذكاء التوليدي',
 'Responsible AI / Security / Governance':'الذكاء المسؤول والأمن والحوكمة',
 'AI Software Engineering':'هندسة برمجيات الذكاء الاصطناعي',
 'Architecture / Infrastructure':'المعمارية والبنية التحتية',
 'Business / Professional Practice':'الأعمال والممارسة المهنية',
};

const $=id=>document.getElementById(id);
let BANK, QUESTIONS=[], WEIGHTS={}, state, lang='ar', activeExam=null;

function t(key,...args){const v=I18N[lang][key];return typeof v==='function'?v(...args):(v??key)}
function domainLabel(domain){return lang==='ar'?(DOMAIN_AR[domain]||domain):domain}
function secureRng(){if(globalThis.crypto?.getRandomValues){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296}return Math.random()}
function save(){state.examV2=state.examV2||{};state.examV2.lang=lang;state.examV2.theme=document.documentElement.dataset.theme||'light';state.examV2.active=activeExam;state.updated_at=new Date().toISOString();void saveState(state)}
function showScreen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');scrollTo({top:0,behavior:'smooth'})}
function qById(id){return QUESTIONS.find(q=>q.id===id)}
function localizedQuestion(q){return lang==='ar'?q.question:q.question_en}
function localizedOptions(q){return lang==='ar'?q.options:q.options_en}
function localizedExplanation(q){return lang==='ar'?q.explanation:q.explanation_en}

function applyLanguage(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';$('langBtn').textContent=lang==='ar'?'EN':'العربية';document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(I18N[lang][key]&&typeof I18N[lang][key]!=='function')el.textContent=t(key)});renderHome();if($('exam').classList.contains('active'))renderExam();if($('results').classList.contains('active'))renderResults(lastResult)}
function applyTheme(theme){document.documentElement.dataset.theme=theme;$('themeBtn').textContent=theme==='dark'?'🌙':'☀️';save()}

function renderAllocation(){const allocation=weightedAllocation(WEIGHTS,200);$('allocation').innerHTML=Object.entries(allocation).map(([d,n])=>`<div class="allocRow"><div><b>${domainLabel(d)}</b><div class="bar"><i style="width:${WEIGHTS[d]}%"></i></div></div><span>${n} · ${WEIGHTS[d]}%</span></div>`).join('')}
function renderDomains(){const counts=Object.fromEntries(Object.keys(WEIGHTS).map(d=>[d,QUESTIONS.filter(q=>q.domain===d).length]));$('domainGrid').innerHTML=Object.entries(WEIGHTS).map(([d,w],i)=>`<div class="card domainCard"><div class="eyebrow">${String(i+1).padStart(2,'0')}</div><h3>${domainLabel(d)}</h3><div class="domainMeta"><span class="chip">${t('weight')} ${w}%</span><span class="chip">${t('bank')} ${counts[d]}</span></div><div class="domainActions"><select class="select sectionCount" data-domain="${d}"><option value="25">25</option><option value="50" selected>50</option><option value="100">100</option><option value="all">${t('all')} (${counts[d]})</option></select><button class="btn primary startSection" data-domain="${d}">${t('start')}</button></div></div>`).join('');document.querySelectorAll('.startSection').forEach(btn=>btn.onclick=()=>{const d=btn.dataset.domain;const sel=[...document.querySelectorAll('.sectionCount')].find(x=>x.dataset.domain===d);startSection(d,sel.value)})}
function renderHome(){if(!BANK)return;$('bankCount').textContent=QUESTIONS.length;renderAllocation();renderDomains();$('domainSummary').innerHTML=`<div class="stats"><div class="stat"><b>${QUESTIONS.length}</b><small>${t('questions')}</small></div><div class="stat"><b>${Object.keys(WEIGHTS).length}</b><small>${t('domains')}</small></div></div>`;const box=$('resumeBox');if(activeExam&&!activeExam.submitted){box.classList.add('show');$('resumeMeta').textContent=t('resumeText',activeExam.index+1,activeExam.questionIds.length)}else box.classList.remove('show')}

function createExam(mode, questions, domain=null){activeExam={id:`exam-${Date.now()}-${Math.floor(secureRng()*1e6)}`,mode,domain,questionIds:questions.map(q=>q.id),index:0,answers:{},confidence:{},flags:{},optionOrders:buildOptionOrders(questions,secureRng),started_at:new Date().toISOString(),submitted:false};save();showScreen('exam');renderExam()}
function startFull(){createExam('full',sampleWeightedExam(QUESTIONS,WEIGHTS,200,secureRng))}
function startSection(domain,count){createExam('section',sampleSectionExam(QUESTIONS,domain,count,secureRng),domain)}

function selectAnswer(canonicalIndex){const q=qById(activeExam.questionIds[activeExam.index]);activeExam.answers[q.id]=canonicalIndex;save();renderExam()}
function setConfidence(value){const q=qById(activeExam.questionIds[activeExam.index]);if(value==='clear')delete activeExam.confidence[q.id];else if(activeExam.confidence[q.id]===value)delete activeExam.confidence[q.id];else activeExam.confidence[q.id]=value;save();renderExam()}
function move(delta){const next=Math.max(0,Math.min(activeExam.questionIds.length-1,activeExam.index+delta));activeExam.index=next;save();renderExam();scrollTo({top:0,behavior:'smooth'})}
function jump(i){activeExam.index=i;save();renderExam();scrollTo({top:0,behavior:'smooth'})}
function toggleFlag(){const id=activeExam.questionIds[activeExam.index];activeExam.flags[id]=!activeExam.flags[id];if(!activeExam.flags[id])delete activeExam.flags[id];save();renderExam()}

function renderExam(){if(!activeExam)return;const q=qById(activeExam.questionIds[activeExam.index]);if(!q)return;const total=activeExam.questionIds.length;const answered=Object.keys(activeExam.answers).length;$('examModeLabel').textContent=activeExam.mode==='full'?t('fullMode'):t('sectionMode');$('examDomainChip').textContent=activeExam.mode==='full'?`${Object.keys(WEIGHTS).length} ${t('domains')}`:domainLabel(activeExam.domain);$('answeredChip').textContent=`${t('answered')} ${answered}/${total}`;$('examProgress').style.width=`${(activeExam.index+1)/total*100}%`;$('qTopic').textContent=`${domainLabel(q.domain)} · ${q.topic}`;$('qText').textContent=localizedQuestion(q);$('questionCounter').textContent=`${activeExam.index+1} ${t('of')} ${total}`;const localized=localizedOptions(q);const order=activeExam.optionOrders[q.id]||[0,1,2,3];$('options').innerHTML=order.map((canonical,display)=>`<button class="option ${Number(activeExam.answers[q.id])===canonical?'selected':''}" data-answer="${canonical}" aria-pressed="${Number(activeExam.answers[q.id])===canonical}"><span class="letter">${String.fromCharCode(65+display)}</span><span>${localized[canonical]}</span></button>`).join('');document.querySelectorAll('.option').forEach(b=>b.onclick=()=>selectAnswer(Number(b.dataset.answer)));document.querySelectorAll('.confBtn').forEach(b=>b.classList.toggle('on',b.dataset.confidence!=='clear'&&activeExam.confidence[q.id]===b.dataset.confidence));$('flagBtn').textContent=activeExam.flags[q.id]?t('unflag'):t('flag');$('prevBtn').disabled=activeExam.index===0;$('nextBtn').disabled=activeExam.index===total-1;$('palette').innerHTML=activeExam.questionIds.map((id,i)=>`<button class="qjump ${i===activeExam.index?'current':''} ${activeExam.answers[id]!==undefined?'answered':''} ${activeExam.flags[id]?'flagged':''}" data-index="${i}" aria-label="${i+1}">${i+1}</button>`).join('');document.querySelectorAll('.qjump').forEach(b=>b.onclick=()=>jump(Number(b.dataset.index)))}

let lastResult=null;
function submitExam(){if(!activeExam)return;if(!confirm(t('confirmSubmit')))return;const qs=activeExam.questionIds.map(qById).filter(Boolean);const result=scoreExam(qs,activeExam.answers);activeExam.submitted=true;activeExam.submitted_at=new Date().toISOString();state.examV2.history=state.examV2.history||[];state.examV2.history.unshift({id:activeExam.id,mode:activeExam.mode,domain:activeExam.domain,result,submitted_at:activeExam.submitted_at});state.examV2.history=state.examV2.history.slice(0,20);lastResult={result,exam:structuredClone(activeExam),questions:qs};activeExam=null;save();showScreen('results');renderResults(lastResult)}
function renderResults(payload){if(!payload)return;const {result,exam,questions}=payload;$('scorePct').textContent=`${result.percent}%`;$('scoreLabel').textContent=t('scoreText',result.correct,result.total);$('correctKpi').textContent=result.correct;$('wrongKpi').textContent=result.answered-result.correct;$('unansweredKpi').textContent=result.unanswered;const confUsed=Object.keys(exam.confidence||{}).length;$('confidenceKpi').textContent=`${Math.round(confUsed/result.total*100)}%`;$('resultBreakdown').innerHTML=Object.entries(result.perDomain).map(([d,v])=>{const pct=v.total?Math.round(v.correct/v.total*1000)/10:0;return `<div><div class="allocRow"><b>${domainLabel(d)}</b><span>${v.correct}/${v.total} · ${pct}%</span></div><div class="bar"><i style="width:${pct}%"></i></div></div>`}).join('');$('reviewList').innerHTML=questions.map((q,i)=>{const a=exam.answers[q.id];const opts=localizedOptions(q);const answerText=a===undefined?t('notAnswered'):opts[a];const good=Number(a)===q.answer;return `<div class="reviewItem"><div class="qTopic">${i+1}. ${domainLabel(q.domain)} · ${q.topic}</div><b>${localizedQuestion(q)}</b><div class="${good?'answerGood':'answerBad'}"><strong>${t('yourAnswer')}:</strong> ${answerText}</div>${good?'':`<div class="answerGood"><strong>${t('correctAnswer')}:</strong> ${opts[q.answer]}</div>`}<div class="muted">${localizedExplanation(q)}</div></div>`}).join('')}

function resetToHome(){showScreen('home');renderHome()}

$('langBtn').onclick=()=>{lang=lang==='ar'?'en':'ar';save();applyLanguage()};$('themeBtn').onclick=()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');$('homeBtn').onclick=resetToHome;$('startFullBtn').onclick=startFull;$('resumeBtn').onclick=()=>{if(activeExam){showScreen('exam');renderExam()}};$('prevBtn').onclick=()=>move(-1);$('nextBtn').onclick=()=>move(1);$('flagBtn').onclick=toggleFlag;$('submitBtn').onclick=submitExam;$('newExamBtn').onclick=resetToHome;document.querySelectorAll('.confBtn').forEach(b=>b.onclick=()=>setConfidence(b.dataset.confidence));
window.addEventListener('keydown',e=>{if(!$('exam').classList.contains('active')||!activeExam)return;if(['1','2','3','4'].includes(e.key)){const q=qById(activeExam.questionIds[activeExam.index]);const order=activeExam.optionOrders[q.id]||[0,1,2,3];selectAnswer(order[Number(e.key)-1])}else if(e.key==='ArrowRight')move(lang==='ar'?-1:1);else if(e.key==='ArrowLeft')move(lang==='ar'?1:-1)});

async function init(){try{BANK=await loadBank();QUESTIONS=expandConceptBank(BANK.concepts||{});WEIGHTS=BANK.weights||{};if(QUESTIONS.length<1000)throw new Error(t('errorBank'));state=(await loadState())||{};state.examV2=state.examV2||{};lang=state.examV2.lang==='en'?'en':'ar';activeExam=state.examV2.active&&!state.examV2.active.submitted?state.examV2.active:null;document.documentElement.dataset.theme=state.examV2.theme==='dark'?'dark':'light';$('themeBtn').textContent=document.documentElement.dataset.theme==='dark'?'🌙':'☀️';applyLanguage();renderHome();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{}))}catch(error){console.error(error);$('errorBox').textContent=error.message||String(error);$('errorBox').classList.add('show')}}
init();
