import { ACTIVE_TRACK_ID } from './config.js';
import { CORE_I18N, CORE_DEFAULT_LOCALE } from './presentation/coreI18n.js';
import { loadTrackPresentation, resolvePresentationLocale, getPresentationLocale } from './presentation/trackPresentation.js';

let lang='ar',theme='light',rating=0;
let TRACK=null,PRESENTATION=null;
try{const raw=localStorage.getItem('learning-platform.state.v2')||localStorage.getItem('sdaia.state.v1')||'{}';const st=JSON.parse(raw);lang=st?.version===2?(st?.preferences?.lang==='en'?'en':'ar'):(st?.examV2?.lang==='en'?'en':'ar');theme=st?.version===2?(st?.preferences?.theme==='dark'?'dark':'light'):(st?.examV2?.theme==='dark'?'dark':'light')}catch{}
function presentationView(){let locale=CORE_I18N[lang]?lang:CORE_DEFAULT_LOCALE;if(PRESENTATION&&TRACK){try{locale=resolvePresentationLocale(lang,TRACK,PRESENTATION)}catch(error){console.warn('Feedback presentation locale fallback',error)}}const view=getPresentationLocale(PRESENTATION,locale);return{displayName:view?.display_name??TRACK?.id??ACTIVE_TRACK_ID,brand:view?.brand??TRACK?.id??ACTIVE_TRACK_ID}}
function apply(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.documentElement.dataset.theme=theme;document.getElementById('langBtn').textContent=lang==='ar'?'EN':'العربية';document.getElementById('themeBtn').textContent=theme==='dark'?'🌙':'☀️';document.querySelectorAll('[data-i18n]').forEach(el=>{const v=CORE_I18N[lang].feedback[el.dataset.i18n];if(v)el.textContent=v});const p=presentationView();document.getElementById('feedbackBrand').textContent=p.brand;document.title=`${p.displayName} · ${CORE_I18N[lang].feedback.community}`}
function persist(){try{const key='learning-platform.state.v2',raw=localStorage.getItem(key);if(!raw)return;const st=JSON.parse(raw);if(st?.version!==2)return;st.preferences=st.preferences||{};st.preferences.lang=lang;st.preferences.theme=theme;localStorage.setItem(key,JSON.stringify(st))}catch{}}
function issue(title,body){const p=new URLSearchParams({template:'public-feedback.md',title,body});window.open(`https://github.com/oaabahussain/sdaia-ai-engineer/issues/new?${p.toString()}`,'_blank','noopener')}
document.getElementById('langBtn').onclick=()=>{lang=lang==='ar'?'en':'ar';persist();apply()};document.getElementById('themeBtn').onclick=()=>{theme=theme==='dark'?'light':'dark';persist();apply()};
document.getElementById('suggestionForm').onsubmit=e=>{e.preventDefault();const area=document.getElementById('suggestionArea').value,title=document.getElementById('suggestionTitleInput').value.trim(),details=document.getElementById('suggestionDetails').value.trim();issue(`[Suggestion] ${title}`,`## Area\n${area}\n\n## Suggestion\n${details}\n\n---\nSubmitted from the public feedback page.`)};
document.getElementById('contributionForm').onsubmit=e=>{e.preventDefault();const type=document.getElementById('contributionType').value,details=document.getElementById('contributionDetails').value.trim(),source=document.getElementById('contributionSource').value.trim();issue(`[Contribution] ${type}`,`## Type\n${type}\n\n## Proposed contribution\n${details}\n\n## Source or reference\n${source||'Not provided'}\n\n---\nSubmitted from the public feedback page.`)};
document.querySelectorAll('.star').forEach(btn=>btn.onclick=()=>{rating=Number(btn.dataset.rating);document.querySelectorAll('.star').forEach(x=>x.classList.toggle('on',Number(x.dataset.rating)<=rating));document.getElementById('ratingError').classList.remove('show')});
document.getElementById('ratingForm').onsubmit=e=>{e.preventDefault();if(!rating){document.getElementById('ratingError').classList.add('show');return}const useful=document.getElementById('ratingUseful').value,comment=document.getElementById('ratingComment').value.trim();issue(`[Rating] ${rating}/5`,`## Rating\n${rating} / 5\n\n## Most useful part\n${useful}\n\n## Comments\n${comment||'No additional comment'}\n\n---\nSubmitted from the public feedback page.`)};
async function loadPresentation(){const fetchJson=async url=>{const response=await fetch(url,{cache:'no-cache'});if(!response.ok)throw new Error(`Failed to load ${url}: ${response.status}`);return response.json()};try{TRACK=await fetchJson(`./tracks/${ACTIVE_TRACK_ID}/manifest.json`);PRESENTATION=await loadTrackPresentation(fetchJson,TRACK)}catch(error){console.warn('Feedback track presentation unavailable',error);TRACK={id:ACTIVE_TRACK_ID,locales:['ar','en']};PRESENTATION=null}apply()}
apply();void loadPresentation();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{}));
